/* AntCV C2PA signing worker (v1.0)
 * ============================================================
 *
 * Receives a DOCX or PDF generated by AntCV, wraps it with a
 * signed C2PA Content Credentials manifest, and returns the
 * signed asset bytes.
 *
 * Endpoints:
 *   POST /sign        — sign a file
 *   GET  /healthz     — health probe
 *   GET  /capabilities — manifest schema, algorithms, vendor
 *
 * The actual signing is performed by the c2pa-rs core compiled
 * to WASM. The WASM module exposes a single function:
 *
 *   sign_asset(bytes: Uint8Array, manifestJson: string,
 *              signingKeyPem: string, signingCertPem: string,
 *              tsaUrl: string | null) → Uint8Array
 *
 * The returned bytes contain the original asset with an embedded
 * C2PA manifest sealed by a cryptographic signature.
 */

import C2PA_WASM from '../wasm/c2pa.wasm';

interface Env {
  C2PA_SIGNING_KEY_PEM: string;
  C2PA_SIGNING_CERT_PEM: string;
  C2PA_TIMESTAMP_AUTHORITY_URL: string;
  C2PA_CLAIM_GENERATOR: string;
  C2PA_VENDOR: string;
  C2PA_PRODUCT_URL: string;
}

type AssetKind = 'application/pdf' | 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';

interface SignRequest {
  asset_base64: string;
  asset_kind: AssetKind;
  source: {
    tool: string;
    version: string;
    document_kind: 'cv' | 'cover-letter';
    language: string;
    target?: { company?: string; role?: string };
  };
  /** AI generation event, as produced by AntCV. */
  ai_event: {
    model_provider: 'anthropic' | 'openai' | 'mistral' | 'google';
    model_id?: string;
    instruction_type: 'draft' | 'rewrite' | 'translate' | 'enrich' | 'extract';
    user_review: 'pending' | 'reviewed' | 'edited';
  };
  /** Author asserted by the user; goes into the manifest's author assertion. */
  author?: { name?: string; identifier?: string };
  /**
   * v1.50.7 — visual disclosure colour. Tracks the active package's `base`
   * token per locked-source plan §3 / §9.3. Optional: when present, embedded
   * in the `com.antcv.ai_disclosure` assertion so downstream verifiers and
   * the visual watermark renderer pick the same colour as the document
   * itself.
   *
   * Shape: `#RRGGBB`. Anything else is silently dropped (logged via
   * console.warn) so an older PWA that doesn't send it stays compatible.
   */
  visual?: {
    package?: string;             // package id, e.g. "copenhagen-modern"
    package_base_color?: string;  // hex, e.g. "#283556"
  };
}

/** Normalise + validate a hex colour. Returns null on anything that isn't #RRGGBB. */
function normaliseHexColor(raw: unknown): string | null {
  if (typeof raw !== 'string') return null;
  const trimmed = raw.trim();
  if (!/^#[0-9A-Fa-f]{6}$/.test(trimmed)) return null;
  return trimmed.toUpperCase();
}

async function instantiate(env: Env) {
  const memory = new WebAssembly.Memory({ initial: 32, maximum: 512 });
  const importObject = {
    env: { memory },
    // c2pa-rs WASM may import a small number of host functions for
    // randomness, time, and timestamping HTTP calls. Wire them up.
    host: {
      now_ms: () => Date.now(),
      random_u32: () => {
        const buf = new Uint32Array(1);
        crypto.getRandomValues(buf);
        return buf[0];
      },
      // c2pa-rs expects to fetch from the TSA itself via host.
      fetch_tsa: async (urlPtr: number, bodyPtr: number, bodyLen: number) => {
        // Implementation depends on the exact WASM ABI exposed by
        // the c2pa-rs build. Fill in once the WASM module's
        // expected imports are known (see c2pa-rs/wasm-bindgen
        // docs).
        throw new Error('fetch_tsa not yet wired — see README §3.');
      },
    },
  };
  const instance = await WebAssembly.instantiate(C2PA_WASM, importObject);
  return { instance, memory };
}

function buildManifest(env: Env, req: SignRequest): object {
  // C2PA 2.0 manifest structure. The "actions" array uses the
  // c2pa.ai_generated and c2pa.ai_drafted actions to mark AI
  // involvement transparently. Per the AI Act Article 50(2), the
  // marking must be machine-readable, effective, interoperable,
  // and robust — this manifest satisfies all four when sealed by
  // a valid X.509 signature.
  const now = new Date().toISOString();
  return {
    claim_generator: env.C2PA_CLAIM_GENERATOR,
    claim_generator_info: [
      {
        name: 'AntCV',
        version: req.source.version,
        product: env.C2PA_PRODUCT_URL,
        vendor: env.C2PA_VENDOR,
      },
    ],
    title: req.source.document_kind === 'cv'
      ? `CV (${req.source.language})`
      : `Cover Letter (${req.source.language})`,
    format: req.asset_kind,
    assertions: [
      {
        label: 'c2pa.actions',
        data: {
          actions: [
            {
              action: 'c2pa.created',
              when: now,
              softwareAgent: env.C2PA_CLAIM_GENERATOR,
            },
            {
              action: req.ai_event.instruction_type === 'translate'
                ? 'c2pa.translated'
                : 'c2pa.ai_generated',
              when: now,
              softwareAgent: env.C2PA_CLAIM_GENERATOR,
              parameters: {
                'com.adobe.aimodel': req.ai_event.model_provider +
                  (req.ai_event.model_id ? '/' + req.ai_event.model_id : ''),
                'com.antcv.user_review': req.ai_event.user_review,
                'com.antcv.instruction_type': req.ai_event.instruction_type,
              },
            },
          ],
        },
      },
      {
        label: 'stds.schema-org.CreativeWork',
        data: {
          '@context': 'https://schema.org',
          '@type': 'CreativeWork',
          author: req.author?.name
            ? [{ '@type': 'Person', name: req.author.name, identifier: req.author.identifier }]
            : undefined,
          creator: [{ '@type': 'Organization', name: 'AntCV (Kanzen Konsulenter i Nord ApS)' }],
          inLanguage: req.source.language,
          dateCreated: now,
        },
      },
      {
        label: 'com.antcv.ai_disclosure',
        data: {
          version: '2026-05-v1',
          eu_ai_act_article_50_2: true,
          author_responsibility: 'Author retains responsibility for content.',
          providers_available: ['anthropic', 'openai', 'mistral', 'google'],
          provider_used: req.ai_event.model_provider,
          // v1.50.7 — visual disclosure colour. Mirrors the active package's
          // `base` token so the watermark renderer and the document share a
          // palette. Null when the PWA didn't supply visual context.
          visual: (() => {
            const pkg = typeof req.visual?.package === 'string' && req.visual.package.trim() ? req.visual.package.trim() : null;
            const color = normaliseHexColor(req.visual?.package_base_color);
            if (!pkg && !color) return null;
            if (req.visual?.package_base_color && !color) {
              try { console.warn('[c2pa] dropped invalid package_base_color:', req.visual.package_base_color); } catch { /* */ }
            }
            return { package: pkg, package_base_color: color };
          })(),
        },
      },
    ],
  };
}

async function handleSign(req: Request, env: Env): Promise<Response> {
  let body: SignRequest;
  try {
    body = await req.json();
  } catch (e) {
    return json({ error: 'invalid_json', detail: String((e as Error).message) }, 400);
  }
  if (!body.asset_base64 || !body.asset_kind) {
    return json({ error: 'missing_fields', required: ['asset_base64', 'asset_kind'] }, 400);
  }
  const allowedKinds: AssetKind[] = [
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  ];
  if (!allowedKinds.includes(body.asset_kind)) {
    return json({ error: 'unsupported_asset_kind' }, 415);
  }

  // Decode the asset.
  let assetBytes: Uint8Array;
  try {
    const b = atob(body.asset_base64);
    assetBytes = new Uint8Array(b.length);
    for (let i = 0; i < b.length; i++) assetBytes[i] = b.charCodeAt(i);
  } catch (e) {
    return json({ error: 'base64_decode_failed' }, 400);
  }

  const manifest = buildManifest(env, body);

  // Instantiate the WASM module and call sign_asset.
  let instance: WebAssembly.Instance;
  try {
    const r = await instantiate(env);
    instance = r.instance;
  } catch (e) {
    return json({
      error: 'wasm_init_failed',
      detail: String((e as Error).message),
      hint: 'Build c2pa.wasm per README §2 and place it under wasm/c2pa.wasm.',
    }, 503);
  }

  const exports = instance.exports as {
    sign_asset?: (
      bytesPtr: number,
      bytesLen: number,
      manifestPtr: number,
      manifestLen: number,
      keyPtr: number,
      keyLen: number,
      certPtr: number,
      certLen: number,
      tsaPtr: number,
      tsaLen: number,
    ) => number;
  };

  if (!exports.sign_asset) {
    return json({
      error: 'wasm_missing_export',
      hint: 'The expected export sign_asset is not present. See README §2 for the required c2pa-rs build flags.',
    }, 503);
  }

  // Real signing call would marshal the parameters into WASM
  // memory, call sign_asset, read the result back. The current
  // scaffold returns the asset unchanged with a manifest preview,
  // so the caller can see the manifest the worker WOULD have
  // sealed.
  const previewResponse = {
    signed: false,
    reason: 'wasm_module_placeholder',
    manifest_preview: manifest,
    next_steps: [
      'Build c2pa-rs WASM (see README §2).',
      'Provision signing certificate (see README §3).',
      'Set worker secrets C2PA_SIGNING_KEY_PEM, C2PA_SIGNING_CERT_PEM, C2PA_TIMESTAMP_AUTHORITY_URL.',
      'Replace placeholder return with the real WASM call (lines marked TODO in src/index.ts).',
    ],
  };
  return json(previewResponse, 200);
}

async function handleCapabilities(env: Env): Promise<Response> {
  return json({
    claim_generator: env.C2PA_CLAIM_GENERATOR,
    vendor: env.C2PA_VENDOR,
    product_url: env.C2PA_PRODUCT_URL,
    supported_asset_kinds: [
      'application/pdf',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    ],
    signing_algorithms: ['ES256', 'PS256'],
    manifest_specification: 'C2PA 2.0',
    ai_actions_emitted: ['c2pa.created', 'c2pa.ai_generated', 'c2pa.translated'],
    eu_ai_act_article_50_2: true,
  });
}

async function handleHealth(): Promise<Response> {
  return json({ ok: true, service: 'antcv-c2pa-worker' });
}

function json(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data, null, 2), {
    status,
    headers: { 'content-type': 'application/json; charset=utf-8' },
  });
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    if (request.method === 'GET' && url.pathname === '/healthz') {
      return handleHealth();
    }
    if (request.method === 'GET' && url.pathname === '/capabilities') {
      return handleCapabilities(env);
    }
    if (request.method === 'POST' && url.pathname === '/sign') {
      return handleSign(request, env);
    }
    return json({ error: 'not_found' }, 404);
  },
};
